# Generated by Django 3.0.6 on 2020-06-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='es_mayorista',
            field=models.BooleanField(default=False),
        ),
    ]
