# Generated by Django 3.0.6 on 2020-06-01 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0002_auto_20200601_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='es_cliente',
        ),
        migrations.RemoveField(
            model_name='user',
            name='es_mayorista',
        ),
    ]
