# Generated by Django 3.0.6 on 2020-06-07 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0003_auto_20200601_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cliente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Ingrese su genero', max_length=1),
        ),
        migrations.AddField(
            model_name='tbl_mayorista',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', help_text='Ingrese su genero', max_length=1),
        ),
    ]
