# Generated by Django 3.0.6 on 2020-06-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0004_auto_20200607_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_mayorista',
            old_name='fecha_nacimento',
            new_name='fecha_nacimiento',
        ),
    ]
