# Generated by Django 3.0.6 on 2020-06-09 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0005_auto_20200609_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo_usuario_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_tipo_usuario'),
        ),
    ]
