# Generated by Django 3.0.6 on 2020-06-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0006_user_tipo_usuario_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cliente',
            name='tipo_usuario_id',
        ),
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='tipo_usuario_id',
        ),
    ]
