# Generated by Django 3.0.6 on 2020-06-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0007_auto_20200609_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField(help_text='ingresa la direccion del cliente', max_length=200)),
                ('estado', models.BooleanField(blank=True, help_text='seleccione si esta activo o no esta direccion', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='tbl_cliente',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_direccion'),
        ),
    ]
