# Generated by Django 3.0.6 on 2020-06-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0008_auto_20200610_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='direccion',
            field=models.TextField(blank=True, help_text='Ingrese la direccion de la empresa', max_length=200, null=True),
        ),
    ]
