# Generated by Django 3.0.6 on 2020-06-10 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0009_tbl_mayorista_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(help_text='Ingrese el nombre el producto', max_length=100)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad del producto')),
                ('precio_unitario', models.FloatField(help_text='Ingrese el precio unitario del producto')),
                ('precio_total', models.FloatField(help_text='precio total en inventario')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_categoria')),
                ('mayorista', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantida vendida')),
                ('precio_unitario', models.FloatField(help_text='Ingrese el precio unitario del producto')),
                ('precio_total', models.FloatField(help_text='Ingrese el precio total de la venta')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_cliente')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_producto')),
            ],
        ),
    ]
