# Generated by Django 3.0.6 on 2020-06-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0010_tbl_categoria_tbl_producto_tbl_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cliente',
            name='direccion',
        ),
    ]
