# Generated by Django 3.0.6 on 2020-06-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0011_remove_tbl_cliente_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_direccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente'),
        ),
    ]
