# Generated by Django 3.0.6 on 2020-06-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0012_tbl_direccion_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cliente',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='photos_perfil'),
        ),
    ]
