# Generated by Django 3.0.6 on 2020-06-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0013_tbl_cliente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='foto_producto1',
            field=models.ImageField(null=True, upload_to='foto_producto'),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='foto_producto2',
            field=models.ImageField(null=True, upload_to='foto_producto'),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='foto_producto3',
            field=models.ImageField(null=True, upload_to='foto_producto'),
        ),
    ]
