# Generated by Django 3.0.6 on 2020-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0014_auto_20200614_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='photos_perfil_proveedor'),
        ),
        migrations.AlterField(
            model_name='tbl_cliente',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='photos_perfil_cliente'),
        ),
    ]
