# Generated by Django 3.0.6 on 2020-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0015_auto_20200614_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_venta',
            name='precio_total',
            field=models.DecimalField(decimal_places=3, help_text='Ingrese el precio total de la venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tbl_venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=3, help_text='Ingrese el precio unitario del producto', max_digits=10),
        ),
    ]
