# Generated by Django 3.0.6 on 2020-06-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0016_auto_20200614_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_venta',
            name='fecha_hora_realizada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
