# Generated by Django 3.0.6 on 2020-06-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0017_tbl_venta_fecha_hora_realizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_venta',
            name='fecha_hora_realizada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
