# Generated by Django 3.0.6 on 2020-06-15 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0019_tbl_barrio_canton_tbl_departamento_tbl_municipio'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='barrio_canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_barrio_canton'),
        ),
    ]
