# Generated by Django 3.0.6 on 2020-06-15 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0020_tbl_mayorista_barrio_canton'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_realizado', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(help_text='Ingrese la cantidad de unidades')),
                ('precio_unitario', models.DecimalField(decimal_places=3, help_text='Ingrese el precio unitario de venta', max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=3, help_text='Ingrese el precio total', max_digits=10)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_producto')),
            ],
        ),
    ]
