# Generated by Django 3.0.6 on 2020-06-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0021_tbl_cesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cesta',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ingrese el precio total', max_digits=10, null=True),
        ),
    ]
