# Generated by Django 3.0.7 on 2020-06-18 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0022_auto_20200615_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_sub_categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categoria', models.CharField(help_text='Ingrese la subcategoria', max_length=50)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_categoria')),
            ],
        ),
    ]
