# Generated by Django 3.0.7 on 2020-06-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0023_tbl_sub_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_categoria',
            name='icono',
            field=models.ImageField(null=True, upload_to='iconos_cate'),
        ),
    ]
