# Generated by Django 3.0.7 on 2020-06-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0024_tbl_categoria_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_categoria',
            name='icono',
            field=models.ImageField(null=True, upload_to='iconos_cate', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto1',
            field=models.ImageField(null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto2',
            field=models.ImageField(null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto3',
            field=models.ImageField(null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
    ]
