# Generated by Django 3.0.7 on 2020-06-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0025_auto_20200619_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cliente',
            name='foto_perfil',
            field=models.ImageField(null=True, upload_to='fotoPerfilCliente', verbose_name='Imagen'),
        ),
    ]
