# Generated by Django 3.0.7 on 2020-06-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0026_auto_20200620_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotoPerfilCliente', verbose_name='Imagen'),
        ),
    ]
