# Generated by Django 3.0.7 on 2020-06-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0027_auto_20200620_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='pais_id',
        ),
    ]
