# Generated by Django 3.0.7 on 2020-06-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0028_auto_20200620_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='barrio_caton',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mayorista',
            name='departamento',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mayorista',
            name='municipio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_mayorista',
            name='pais',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
