# Generated by Django 3.0.7 on 2020-06-20 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0029_auto_20200620_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cliente',
            name='nombre_negocio',
        ),
    ]
