# Generated by Django 3.0.7 on 2020-06-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0030_remove_tbl_cliente_nombre_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_perfil_proveedor'),
        ),
    ]
