# Generated by Django 3.0.7 on 2020-06-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0031_auto_20200621_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='foto_perfil_proveedor', verbose_name='Imagen'),
        ),
    ]
