# Generated by Django 3.0.7 on 2020-06-21 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0032_auto_20200621_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='barrio_caton',
        ),
    ]
