# Generated by Django 3.0.7 on 2020-06-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0033_remove_tbl_mayorista_barrio_caton'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='barrio_caton',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
