# Generated by Django 3.0.7 on 2020-06-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0034_tbl_mayorista_barrio_caton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='barrio_canton',
        ),
    ]
