# Generated by Django 3.0.7 on 2020-06-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0035_remove_tbl_mayorista_barrio_canton'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_direccion',
            name='direccion',
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='barrio_canton',
            field=models.TextField(help_text='Ingrese el departamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='calle',
            field=models.TextField(help_text='Ingrese el departamento', max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='departamento',
            field=models.TextField(help_text='Ingrese el departamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='municipio',
            field=models.TextField(help_text='Ingrese el departamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='pais',
            field=models.TextField(help_text='Ingrese el departamento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tbl_direccion',
            name='referencia',
            field=models.TextField(help_text='Ingrese el departamento', max_length=200, null=True),
        ),
    ]
