# Generated by Django 3.0.7 on 2020-06-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0036_auto_20200622_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_cliente',
            name='pais_id',
        ),
    ]
