# Generated by Django 3.0.7 on 2020-06-26 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0037_remove_tbl_cliente_pais_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_direccion',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente'),
        ),
    ]
