# Generated by Django 3.0.7 on 2020-06-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0038_auto_20200626_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_direccion',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente'),
        ),
    ]
