# Generated by Django 3.0.7 on 2020-06-26 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0039_auto_20200626_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cliente',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
