# Generated by Django 3.0.7 on 2020-06-28 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0040_auto_20200626_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_cliente',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='fotoPerfilCliente', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='foto_perfil',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='foto_perfil_proveedor', verbose_name='Imagen'),
        ),
    ]
