# Generated by Django 3.0.7 on 2020-06-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0041_auto_20200628_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='precio_total',
            field=models.FloatField(blank=True, help_text='precio total en inventario', null=True),
        ),
    ]
