# Generated by Django 3.0.7 on 2020-06-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0042_auto_20200628_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_venta',
            name='precio_total',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Ingrese el precio total de la venta', max_digits=10, null=True),
        ),
    ]
