# Generated by Django 3.0.7 on 2020-07-01 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0043_auto_20200629_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='costo_envio',
            field=models.FloatField(help_text='Costo del envio', null=True),
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='info_producto',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
