# Generated by Django 3.0.7 on 2020-07-01 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0044_auto_20200701_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='medio_de_envio',
            field=models.CharField(help_text='empresa por donde se envia el producto', max_length=100, null=True),
        ),
    ]
