# Generated by Django 3.0.7 on 2020-07-02 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0046_tbl_venta_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_cesta',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_direccion'),
        ),
    ]
