# Generated by Django 3.0.7 on 2020-07-02 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0054_auto_20200702_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_venta',
            old_name='estado',
            new_name='estado_envio',
        ),
    ]
