# Generated by Django 3.0.7 on 2020-07-03 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0055_auto_20200702_1712'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_comentario_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField(help_text='Ingrese un comentario sobre su experiencia de compra', max_length=500)),
                ('puntaje', models.IntegerField(help_text='Ingrese un puntaja evaluando al vendedor de esta manera ayuda a que otras personas tengan mas confianza para comprar en la tienda')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_producto')),
            ],
        ),
    ]
