# Generated by Django 3.0.7 on 2020-07-03 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0056_tbl_comentario_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_comentario_producto',
            name='producto',
        ),
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_venta'),
        ),
    ]
