# Generated by Django 3.0.7 on 2020-07-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0057_auto_20200703_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_comentario_producto',
            name='venta',
        ),
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_producto'),
        ),
    ]
