# Generated by Django 3.0.7 on 2020-07-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0058_auto_20200703_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_mayorista',
            name='objetivo',
            field=models.TextField(help_text='Ingrese informacion de su empresa al sector a que se dedica y su objetivo', max_length=300, null=True),
        ),
    ]
