# Generated by Django 3.0.7 on 2020-07-08 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0059_tbl_mayorista_objetivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_seguidores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
    ]
