# Generated by Django 3.0.8 on 2020-07-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0060_tbl_seguidores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='fecha_registro',
            field=models.DateField(blank=True, null=True),
        ),
    ]
