# Generated by Django 3.0.8 on 2020-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0061_tbl_producto_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seguidores',
            name='fecha_de_seguidor',
            field=models.DateTimeField(null=True),
        ),
    ]
