# Generated by Django 3.0.8 on 2020-07-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0062_tbl_seguidores_fecha_de_seguidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto1',
            field=models.ImageField(blank=True, null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='foto_producto3',
            field=models.ImageField(blank=True, null=True, upload_to='foto_producto', verbose_name='Imagen'),
        ),
    ]
