# Generated by Django 3.0.8 on 2020-07-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0064_tbl_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='url',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
