# Generated by Django 3.0.8 on 2020-08-02 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0065_tbl_producto_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_sub_categoria',
            new_name='tbl_sub_categoria1',
        ),
        migrations.CreateModel(
            name='tbl_sub_categoria2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_categoria2', models.CharField(help_text='Ingrese subcategoria nivel 3', max_length=50)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_sub_categoria1')),
            ],
        ),
    ]
