# Generated by Django 3.0.8 on 2020-08-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0066_auto_20200802_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='sub_categoria2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_sub_categoria2'),
        ),
    ]
