# Generated by Django 3.0.8 on 2020-08-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0067_auto_20200802_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='foto_prueba1',
            field=models.ImageField(blank=True, null=True, upload_to='foto_prueba', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='foto_prueba2',
            field=models.ImageField(blank=True, null=True, upload_to='foto_prueba', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='foto_prueba3',
            field=models.ImageField(blank=True, null=True, upload_to='foto_prueba', verbose_name='Image'),
        ),
    ]
