# Generated by Django 3.0.8 on 2020-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0068_auto_20200805_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_comentario_producto',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
