# Generated by Django 3.0.8 on 2020-08-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0069_tbl_comentario_producto_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_producto',
            name='sub_categoria2',
        ),
    ]
