# Generated by Django 3.0.8 on 2020-08-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0070_remove_tbl_producto_sub_categoria2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_sub_categoria2',
        ),
    ]
