# Generated by Django 3.0.8 on 2020-08-08 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0071_delete_tbl_sub_categoria2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='sub_categoria1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_sub_categoria1'),
        ),
    ]
