# Generated by Django 3.0.8 on 2020-08-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0072_tbl_producto_sub_categoria1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='barrio_caton',
        ),
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='tbl_mayorista',
            name='pais',
        ),
        migrations.AddField(
            model_name='tbl_mayorista',
            name='barrio_canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_barrio_canton'),
        ),
    ]
