# Generated by Django 3.0.8 on 2020-08-14 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0073_auto_20200810_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='barrio_canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_barrio_canton'),
        ),
    ]
