# Generated by Django 3.0.8 on 2020-08-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0074_auto_20200813_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ingrese su numero de telefono', max_length=8, null=True),
        ),
    ]
