# Generated by Django 3.0.8 on 2020-08-14 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0075_auto_20200813_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='barrio_canton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_barrio_canton'),
        ),
        migrations.AlterField(
            model_name='tbl_mayorista',
            name='telefono',
            field=models.CharField(help_text='Ingrese su numero de telefono', max_length=8),
        ),
    ]
