# Generated by Django 3.0.8 on 2020-08-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0076_auto_20200813_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mensajes_enviados_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(help_text='Ingrese el mensaje', max_length=500)),
                ('fecha_hora', models.DateTimeField(help_text='Ingrese la fecha y la hora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mensajes_enviados_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpo', models.TextField(help_text='Ingrese el mensaje', max_length=500)),
                ('fecha_hora', models.DateField(help_text='Ingrese la fecha y la hora')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_respuesta_mayorista_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensajes_enviados_cliente')),
                ('respuesta_mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensajes_enviados_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_respuesta_cliente_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensajes_enviados_mayorista')),
                ('respuesta_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensajes_enviados_cliente')),
            ],
        ),
    ]
