# Generated by Django 3.0.8 on 2020-08-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0077_tbl_mensajes_enviados_cliente_tbl_mensajes_enviados_mayorista_tbl_respuesta_cliente_mayorista_tbl_re'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_mensajes_enviados_mayorista',
            name='fecha_hora',
            field=models.DateTimeField(help_text='Ingrese la fecha y la hora'),
        ),
    ]
