# Generated by Django 3.0.8 on 2020-08-19 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0078_auto_20200817_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_favoritos',
            name='grupo_privado',
            field=models.CharField(help_text='Escriba nombre grupo privado', max_length=50, null=True),
        ),
    ]
