# Generated by Django 3.0.8 on 2020-08-19 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0079_tbl_favoritos_grupo_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_favoritos',
            name='grupo_privado',
        ),
    ]
