# Generated by Django 3.0.8 on 2020-08-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0080_remove_tbl_favoritos_grupo_privado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_seguidores',
            name='grupo_privado',
            field=models.CharField(help_text='Escriba nombre grupo privado', max_length=50, null=True),
        ),
    ]
