# Generated by Django 3.0.8 on 2020-08-25 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0081_tbl_seguidores_grupo_privado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_mensajes_enviados_mayorista',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='tbl_mensajes_enviados_mayorista',
            name='mayorista',
        ),
        migrations.RemoveField(
            model_name='tbl_respuesta_cliente_mayorista',
            name='mensaje_mayorista',
        ),
        migrations.RemoveField(
            model_name='tbl_respuesta_cliente_mayorista',
            name='respuesta_cliente',
        ),
        migrations.RemoveField(
            model_name='tbl_respuesta_mayorista_cliente',
            name='mensaje_cliente',
        ),
        migrations.RemoveField(
            model_name='tbl_respuesta_mayorista_cliente',
            name='respuesta_mayorista',
        ),
        migrations.DeleteModel(
            name='tbl_mensajes_enviados_cliente',
        ),
        migrations.DeleteModel(
            name='tbl_mensajes_enviados_mayorista',
        ),
        migrations.DeleteModel(
            name='tbl_respuesta_cliente_mayorista',
        ),
        migrations.DeleteModel(
            name='tbl_respuesta_mayorista_cliente',
        ),
    ]
