# Generated by Django 3.0.8 on 2020-08-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0082_auto_20200825_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_mensaje_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('grupo_privado', models.CharField(max_length=500)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_mensaje_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha_envio', models.DateTimeField(null=True)),
                ('grupo_privado', models.CharField(max_length=500)),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_respuesta_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensaje_cliente')),
                ('mensaje_mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensaje_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_respuesta_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensaje_cliente')),
                ('mensaje_mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mensaje_mayorista')),
            ],
        ),
    ]
