# Generated by Django 3.0.8 on 2020-08-31 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0083_tbl_mensaje_cliente_tbl_mensaje_mayorista_tbl_respuesta_cliente_tbl_respuesta_mayorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.TextField(help_text='Ingrese el canal unico', max_length=10000)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
