# Generated by Django 3.0.8 on 2020-08-31 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0084_tbl_clientes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_clientes',
            new_name='tbl_clients_connect',
        ),
    ]
