# Generated by Django 3.0.8 on 2020-08-31 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0085_auto_20200831_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_clients_connect',
            name='estado',
            field=models.BooleanField(help_text='seleccione para saber si esta conectado', null=True),
        ),
    ]
