# Generated by Django 3.0.8 on 2020-08-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0086_tbl_clients_connect_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_clients_connect',
            name='fecha_connect',
            field=models.DateTimeField(blank=True, help_text='fecha y hora de conecccion', null=True),
        ),
        migrations.AddField(
            model_name='tbl_clients_connect',
            name='fecha_disconnect',
            field=models.DateField(blank=True, help_text='fecha y hora de desconeccion', null=True),
        ),
    ]
