# Generated by Django 3.0.8 on 2020-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0087_auto_20200831_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_clients_connect',
            name='fecha_disconnect',
            field=models.DateTimeField(blank=True, help_text='fecha y hora de desconeccion', null=True),
        ),
    ]
