# Generated by Django 3.0.8 on 2020-09-05 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0088_auto_20200831_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_respuesta_mayorista',
        ),
    ]
