# Generated by Django 3.0.8 on 2020-09-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0089_delete_tbl_respuesta_mayorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_respuesta_cliente',
            name='mensaje_cliente',
        ),
        migrations.RemoveField(
            model_name='tbl_respuesta_cliente',
            name='mensaje_mayorista',
        ),
        migrations.DeleteModel(
            name='tbl_mensaje_mayorista',
        ),
        migrations.DeleteModel(
            name='tbl_respuesta_cliente',
        ),
    ]
