# Generated by Django 3.0.8 on 2020-09-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0090_auto_20200905_1628'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_mensaje_cliente',
        ),
    ]
