# Generated by Django 3.0.8 on 2020-09-06 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0091_delete_tbl_mensaje_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_bandeja_de_salida_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(null=True)),
                ('grupo', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_bandeja_de_salida_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(null=True)),
                ('grupo', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_bandeja_de_entrada_mayorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(null=True)),
                ('grupo', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_bandeja_de_entrada_cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(null=True)),
                ('grupo', models.CharField(max_length=40)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cliente')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
            ],
        ),
    ]
