# Generated by Django 3.0.8 on 2020-09-06 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0092_tbl_bandeja_de_entrada_cliente_tbl_bandeja_de_entrada_mayorista_tbl_bandeja_de_salida_cliente_tbl_ba'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_bandeja_de_salida_cliente',
            name='mensaje_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_bandeja_de_entrada_cliente'),
        ),
        migrations.AddField(
            model_name='tbl_bandeja_de_salida_mayorista',
            name='mensaje_entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_bandeja_de_entrada_mayorista'),
        ),
    ]
