# Generated by Django 3.0.8 on 2020-09-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0093_auto_20200905_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_bandeja_de_salida_cliente',
            name='mensaje_entrada',
        ),
        migrations.AddField(
            model_name='tbl_bandeja_de_entrada_cliente',
            name='mensaje_salida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_bandeja_de_salida_cliente'),
        ),
    ]
