# Generated by Django 3.0.8 on 2020-09-06 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0094_auto_20200906_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_bandeja_de_salida_mayorista',
            name='mensaje_entrada',
        ),
        migrations.AddField(
            model_name='tbl_bandeja_de_entrada_mayorista',
            name='mensaje_salida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_bandeja_de_salida_mayorista'),
        ),
    ]
