# Generated by Django 3.0.8 on 2020-10-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0095_auto_20200906_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='precio_venta',
            field=models.FloatField(help_text='Ingrese el precio unitario de venta del producto', null=True),
        ),
        migrations.AlterField(
            model_name='tbl_producto',
            name='precio_unitario',
            field=models.FloatField(help_text='Ingrese el precio unitario de compra del producto'),
        ),
    ]
