# Generated by Django 3.0.8 on 2020-10-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0096_auto_20201024_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='codigo_producto',
            field=models.CharField(help_text='Ingrese el codigo del producto', max_length=50, null=True),
        ),
    ]
