# Generated by Django 3.0.8 on 2020-10-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0097_tbl_producto_codigo_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='precio_total_venta',
            field=models.FloatField(help_text='Ingrese el precio total de venta', null=True),
        ),
    ]
