# Generated by Django 3.0.8 on 2020-10-25 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0098_tbl_producto_precio_total_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_venta',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_direccion'),
        ),
    ]
