# Generated by Django 3.0.8 on 2020-10-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0099_auto_20201025_1357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
