# Generated by Django 3.0.8 on 2020-10-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0100_auto_20201025_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('username', 'first_name', 'last_name')},
        ),
    ]
