# Generated by Django 3.0.8 on 2020-10-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0101_auto_20201026_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_factura',
            name='Fecha_hora',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se genera la factura', null=True),
        ),
        migrations.AddField(
            model_name='tbl_factura',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tbl_factura',
            name='direccion',
            field=models.TextField(blank=True, help_text='Direccion del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tbl_factura',
            name='nit',
            field=models.CharField(blank=True, help_text='Nit de la empresa', max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='tbl_factura',
            name='numero_factura',
            field=models.CharField(blank=True, help_text='Numero de factura', max_length=50, null=True),
        ),
    ]
