# Generated by Django 3.0.8 on 2020-10-27 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0102_auto_20201027_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_venta',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_factura'),
        ),
    ]
