# Generated by Django 3.0.8 on 2020-10-29 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0103_tbl_venta_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_venta',
            name='cliente_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_cliente'),
        ),
    ]
