# Generated by Django 3.0.8 on 2020-10-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0104_auto_20201029_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='codigo_barra',
            field=models.TextField(blank=True, help_text='cogigo de barra', null=True),
        ),
    ]
