# Generated by Django 3.1.3 on 2020-11-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0106_auto_20201103_1934'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set(),
        ),
    ]
