# Generated by Django 3.1.3 on 2020-11-04 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0107_auto_20201104_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_caja',
            name='mayoristas',
        ),
        migrations.AddField(
            model_name='tbl_caja',
            name='mayorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista'),
        ),
    ]
