# Generated by Django 3.1.3 on 2020-11-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0108_auto_20201104_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(help_text='Ingrese el nombre de la campañia', max_length=100)),
                ('representante', models.CharField(blank=True, help_text='Nombre del algun representante de la Empresa', max_length=50, null=True)),
                ('contacto', models.CharField(help_text='Numero de contanto de la empresa', max_length=10)),
                ('direccion', models.TextField(help_text='Direccion de la compañia o empresa', max_length=200)),
            ],
        ),
    ]
