# Generated by Django 3.1.3 on 2020-11-07 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0109_tbl_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_proveedor',
            name='mayorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista'),
        ),
    ]
