# Generated by Django 3.1.3 on 2020-11-16 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0110_tbl_proveedor_mayorista'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_compras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de producto que se compra')),
                ('precio_compra', models.DecimalField(decimal_places=3, help_text='Precio de compra del producto', max_digits=10)),
                ('total_compra', models.DecimalField(decimal_places=3, help_text='Ingrese el total de la compra', max_digits=10)),
                ('cajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cajero')),
                ('mayorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_mayorista')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superStore.tbl_proveedor')),
            ],
        ),
    ]
