# Generated by Django 3.1.3 on 2020-11-17 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0111_tbl_compras'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_compras',
            name='proveedor',
        ),
        migrations.AddField(
            model_name='tbl_producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_proveedor'),
        ),
    ]
