# Generated by Django 3.1.3 on 2020-11-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0112_auto_20201117_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_producto',
            name='fecha_registro',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
