# Generated by Django 3.1.3 on 2020-11-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0113_auto_20201117_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_producto',
            name='fecha_edicion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
