# Generated by Django 3.1.3 on 2020-11-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0114_tbl_producto_fecha_edicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_compras',
            name='fecha_compra',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
