# Generated by Django 3.1.3 on 2020-11-22 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superStore', '0115_tbl_compras_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_venta',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superStore.tbl_cajero'),
        ),
    ]
